r"""Tailored Intelligence Event Browser.

 _______                        __ _______ __        __ __
|   _   .----.-----.--.--.--.--|  |   _   |  |_.----|__|  |--.-----.
|.  1___|   _|  _  |  |  |  |  _  |   1___|   _|   _|  |    <|  -__|
|.  |___|__| |_____|________|_____|____   |____|__| |__|__|__|_____|
|:  1   |                         |:  1   |
|::.. . |                         |::.. . |             FalconPy
`-------'                         `-------'

 ______   ____  ____  _       ___   ____     ___  ___
|      T /    Tl    j| T     /   \ |    \   /  _]|   \
|      |Y  o  | |  T | |    Y     Y|  D  ) /  [_ |    \
l_j  l_j|     | |  | | l___ |  O  ||    / Y    _]|  D  Y
  |  |  |  _  | |  | |     T|     ||    \ |   [_ |     |
  |  |  |  |  | j  l |     |l     !|  .  Y|     T|     |
  l__j  l__j__j|____jl_____j \___/ l__j\_jl_____jl_____j

 ____  ____   ______    ___  _      _      ____   ____    ___  ____     __    ___
l    j|    \ |      T  /  _]| T    | T    l    j /    T  /  _]|    \   /  ]  /  _]
 |  T |  _  Y|      | /  [_ | |    | |     |  T Y   __j /  [_ |  _  Y /  /  /  [_
 |  | |  |  |l_j  l_jY    _]| l___ | l___  |  | |  T  |Y    _]|  |  |/  /  Y    _]
 |  | |  |  |  |  |  |   [_ |     T|     T |  | |  l_ ||   [_ |  |  /   \_ |   [_
 j  l |  |  |  |  |  |     T|     ||     | j  l |     ||     T|  |  \     ||     T
|____jl__j__j  l__j  l_____jl_____jl_____j|____jl___,_jl_____jl__j__j\____jl_____j

 ____   ____    ___   __    __  _____   ___  ____
|    \ |    \  /   \ |  T__T  T/ ___/  /  _]|    \
|  o  )|  D  )Y     Y|  |  |  (   \_  /  [_ |  D  )
|     T|    / |  O  ||  |  |  |\__  TY    _]|    /
|  O  ||    \ |     |l  `  '  !/  \ ||   [_ |    \
|     ||  .  Yl     ! \      / \    ||     T|  .  Y
l_____jl__j\_j \___/   \_/\_/   \___jl_____jl__j\_j

                    Tailored Intelligence Event Browser
                    Uses: TailoredIntelligence
                    Scope: tailored-intelligence:read

A Kivy desktop application for browsing CrowdStrike Tailored Intelligence
events — customer-environment-specific threat events generated by active
tailored rules.

Features
--------
  - Card-based event feed (RecycleView): type, headline, confidence, timestamp
  - Tap a card to open a detail screen with full event body and source rule
  - Rules tab: list active tailored intelligence rules
  - Date range filter for narrowing the event window
  - Overlay error screen when credentials are missing or auth fails

Authentication
--------------
  Credentials are resolved in this order (first non-empty value wins):
    1. -k / -s command-line arguments
    2. FALCON_CLIENT_ID / FALCON_CLIENT_SECRET environment variables

  If credentials are absent or auth fails, an error overlay is shown.

Usage
-----
    # Via environment variables:
    FALCON_CLIENT_ID=xxx FALCON_CLIENT_SECRET=yyy \
        pipenv run python3 tailored_intel_browser.py

    # Via command-line arguments:
    pipenv run python3 tailored_intel_browser.py -k <client_id> -s <client_secret>

Required API scope
------------------
  tailored-intelligence:read
"""
# pylint: disable=too-many-lines
# pylint: disable=too-many-locals,too-many-statements
# pylint: disable=too-many-instance-attributes,too-many-branches
# pylint: disable=wrong-import-position,wrong-import-order,import-error

import argparse
import json
import os
import sys
import threading
from datetime import datetime, timedelta
from typing import Optional

# ---------------------------------------------------------------------------
# PRE-IMPORT argv scrubbing — MUST happen before any Kivy import.
#
# Kivy processes sys.argv at import time and treats -k (fake-fullscreen) and
# -s (save) as its own flags.  Scrub our credential flags out of sys.argv
# now, store the values in module-level variables, and restore argv minus our
# flags so Kivy never sees -k/-s.
# ---------------------------------------------------------------------------

def _scrub_credentials_from_argv() -> tuple:
    """Remove -k/-s from sys.argv before Kivy imports consume them.

    Returns (client_id, client_secret) extracted from sys.argv, or ("", "")
    if not present.  sys.argv is modified in-place to strip the flags.
    """
    _parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    _parser.add_argument("-k", dest="client_id", default="", metavar="CLIENT_ID")
    _parser.add_argument("-s", dest="client_secret", default="", metavar="CLIENT_SECRET")
    _args, _remainder = _parser.parse_known_args()
    sys.argv = sys.argv[:1] + _remainder
    return _args.client_id, _args.client_secret


_PRE_IMPORT_CLIENT_ID, _PRE_IMPORT_CLIENT_SECRET = _scrub_credentials_from_argv()

os.environ["KIVY_NO_ARGS"] = "1"

from kivy.app import App
from kivy.clock import Clock
from kivy.lang import Builder
from kivy.properties import (
    BooleanProperty,
    ListProperty,
    NumericProperty,
    ObjectProperty,
    StringProperty,
)
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.label import Label
from kivy.uix.recycleview import RecycleView
from kivy.uix.recycleview.views import RecycleDataViewBehavior
from kivy.uix.screenmanager import Screen, ScreenManager
from kivy.uix.widget import Widget
from falconpy import TailoredIntelligence

# ---------------------------------------------------------------------------
# Kivy KV layout definitions
# ---------------------------------------------------------------------------

KV = r"""
#:import dp kivy.metrics.dp

<RootLayout>:
    orientation: 'vertical'
    padding: dp(0)
    spacing: dp(0)

<TopBar>:
    orientation: 'horizontal'
    size_hint_y: None
    height: dp(56)
    padding: [dp(16), dp(8)]
    spacing: dp(12)
    canvas.before:
        Color:
            rgba: 0.13, 0.13, 0.16, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: 'Tailored Intel Browser'
        font_size: sp(18)
        bold: True
        color: 0.9, 0.4, 0.2, 1
        size_hint_x: None
        width: dp(260)
        halign: 'left'
        text_size: self.size

    Label:
        id: status_label
        text: '● Disconnected'
        color: 0.6, 0.6, 0.6, 1
        size_hint_x: None
        width: dp(160)
        font_size: sp(13)

    Widget:  # spacer
        size_hint_x: 1

    Button:
        id: refresh_btn
        text: 'Refresh'
        size_hint_x: None
        width: dp(90)
        on_press: app.on_refresh_pressed()
        background_color: 0.2, 0.4, 0.8, 1
        background_normal: ''

<TabBar>:
    orientation: 'horizontal'
    size_hint_y: None
    height: dp(44)
    padding: [dp(8), dp(4)]
    spacing: dp(4)
    canvas.before:
        Color:
            rgba: 0.1, 0.1, 0.13, 1
        Rectangle:
            pos: self.pos
            size: self.size

<TabButton>:
    size_hint_x: None
    width: dp(120)
    background_normal: ''
    background_color: 0.15, 0.15, 0.2, 1
    color: 0.7, 0.7, 0.7, 1
    font_size: sp(13)

<TabButtonActive>:
    TabButton:
        background_color: 0.2, 0.4, 0.8, 1
        color: 1, 1, 1, 1

<EventCard>:
    orientation: 'vertical'
    size_hint_y: None
    height: dp(130)
    padding: [dp(12), dp(8)]
    spacing: dp(4)
    canvas.before:
        Color:
            rgba: self.bg_color
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(6)]

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(22)
        spacing: dp(8)

        Label:
            id: type_badge
            text: root.event_type
            size_hint_x: None
            width: dp(110)
            font_size: sp(11)
            bold: True
            color: 0.4, 0.85, 0.6, 1
            halign: 'left'
            text_size: self.size

        Widget:
            size_hint_x: 1

        Label:
            id: ts_label
            text: root.timestamp
            font_size: sp(11)
            color: 0.55, 0.55, 0.55, 1
            size_hint_x: None
            width: dp(145)
            halign: 'right'
            text_size: self.size

    Label:
        id: headline_label
        text: root.headline
        font_size: sp(13)
        color: 0.9, 0.9, 0.9, 1
        size_hint_y: None
        height: dp(36)
        halign: 'left'
        valign: 'top'
        text_size: self.width, None
        shorten: True
        shorten_from: 'right'

    Label:
        id: summary_label
        text: root.card_summary
        font_size: sp(11)
        color: 0.7, 0.75, 0.8, 1
        size_hint_y: None
        height: dp(32)
        halign: 'left'
        valign: 'top'
        text_size: self.width, None
        shorten: True
        shorten_from: 'right'

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(18)
        spacing: dp(8)

        Label:
            text: 'Confidence:'
            font_size: sp(11)
            color: 0.55, 0.55, 0.55, 1
            size_hint_x: None
            width: dp(70)

        Label:
            id: confidence_label
            text: root.confidence
            font_size: sp(11)
            bold: True
            color: root.confidence_color
            size_hint_x: None
            width: dp(80)

<EventsRecycleView>:
    viewclass: 'EventCard'
    bar_width: dp(10)
    scroll_type: ['bars', 'content']
    bar_color: 0.4, 0.6, 0.9, 0.8
    bar_inactive_color: 0.3, 0.3, 0.4, 0.5
    RecycleBoxLayout:
        id: box_layout
        default_size: None, dp(130)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        spacing: dp(6)
        padding: [dp(8), dp(8)]

<FilterBar>:
    orientation: 'horizontal'
    size_hint_y: None
    height: dp(44)
    padding: [dp(8), dp(6)]
    spacing: dp(8)
    canvas.before:
        Color:
            rgba: 0.1, 0.1, 0.13, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: 'Date range:'
        size_hint_x: None
        width: dp(80)
        color: 0.7, 0.7, 0.7, 1
        font_size: sp(13)

    Button:
        id: range_24h
        text: '24h'
        size_hint_x: None
        width: dp(55)
        on_press: app.on_date_range_pressed('24h')
        background_normal: ''
        background_color: 0.2, 0.5, 0.2, 1
        font_size: sp(12)

    Button:
        id: range_7d
        text: '7d'
        size_hint_x: None
        width: dp(55)
        on_press: app.on_date_range_pressed('7d')
        background_normal: ''
        background_color: 0.15, 0.15, 0.2, 1
        font_size: sp(12)

    Button:
        id: range_30d
        text: '30d'
        size_hint_x: None
        width: dp(55)
        on_press: app.on_date_range_pressed('30d')
        background_normal: ''
        background_color: 0.15, 0.15, 0.2, 1
        font_size: sp(12)

    Button:
        id: range_all
        text: 'All'
        size_hint_x: None
        width: dp(55)
        on_press: app.on_date_range_pressed('all')
        background_normal: ''
        background_color: 0.15, 0.15, 0.2, 1
        font_size: sp(12)

    Widget:
        size_hint_x: 1

    Label:
        id: event_count_label
        text: '0 events'
        color: 0.55, 0.55, 0.55, 1
        font_size: sp(12)
        size_hint_x: None
        width: dp(80)

<PaginationBar>:
    orientation: 'horizontal'
    size_hint_y: None
    height: dp(40)
    padding: [dp(8), dp(4)]
    spacing: dp(6)
    canvas.before:
        Color:
            rgba: 0.08, 0.08, 0.1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Button:
        id: prev_btn
        text: '← Prev'
        size_hint_x: None
        width: dp(80)
        on_press: app.on_prev_page()
        background_normal: ''
        background_color: 0.15, 0.15, 0.2, 1
        font_size: sp(12)

    Label:
        id: page_info_label
        text: 'Page 1 / 1'
        color: 0.7, 0.7, 0.7, 1
        font_size: sp(12)
        size_hint_x: 1
        halign: 'center'
        text_size: self.size

    Button:
        id: next_btn
        text: 'Next →'
        size_hint_x: None
        width: dp(80)
        on_press: app.on_next_page()
        background_normal: ''
        background_color: 0.15, 0.15, 0.2, 1
        font_size: sp(12)

    Label:
        text: 'Per page:'
        size_hint_x: None
        width: dp(65)
        color: 0.7, 0.7, 0.7, 1
        font_size: sp(12)

    Button:
        id: ps_25
        text: '25'
        size_hint_x: None
        width: dp(40)
        on_press: app.on_page_size_change(25)
        background_normal: ''
        background_color: 0.15, 0.15, 0.2, 1
        font_size: sp(12)

    Button:
        id: ps_50
        text: '50'
        size_hint_x: None
        width: dp(40)
        on_press: app.on_page_size_change(50)
        background_normal: ''
        background_color: 0.2, 0.5, 0.2, 1
        font_size: sp(12)

    Button:
        id: ps_100
        text: '100'
        size_hint_x: None
        width: dp(45)
        on_press: app.on_page_size_change(100)
        background_normal: ''
        background_color: 0.15, 0.15, 0.2, 1
        font_size: sp(12)

<RuleCard>:
    orientation: 'vertical'
    size_hint_y: None
    height: dp(70)
    padding: [dp(12), dp(8)]
    spacing: dp(4)
    canvas.before:
        Color:
            rgba: 0.12, 0.15, 0.2, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(6)]

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(22)

        Label:
            id: rule_name
            text: root.rule_name
            font_size: sp(13)
            bold: True
            color: 0.8, 0.85, 1.0, 1
            halign: 'left'
            text_size: self.width, None
            size_hint_x: 1

        Label:
            id: rule_status
            text: root.rule_status
            size_hint_x: None
            width: dp(80)
            font_size: sp(12)
            color: root.rule_status_color
            halign: 'right'
            text_size: self.size

    Label:
        id: rule_type
        text: root.rule_type
        font_size: sp(11)
        color: 0.55, 0.55, 0.55, 1
        halign: 'left'
        text_size: self.width, None
        size_hint_y: None
        height: dp(18)

    Label:
        id: rule_id
        text: root.rule_id
        font_size: sp(10)
        color: 0.4, 0.4, 0.4, 1
        halign: 'left'
        text_size: self.width, None
        size_hint_y: None
        height: dp(16)

<RulesRecycleView>:
    viewclass: 'RuleCard'
    RecycleBoxLayout:
        default_size: None, dp(70)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        spacing: dp(6)
        padding: [dp(8), dp(8)]

<LoadingOverlay>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.6
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: 'Loading…'
        font_size: sp(22)
        color: 1, 1, 1, 0.9
        pos: root.pos
        size: root.size
        halign: 'center'
        valign: 'middle'
        text_size: root.size

<ErrorOverlay>:
    canvas.before:
        Color:
            rgba: 0.08, 0.05, 0.05, 0.97
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        size_hint: 0.7, 0.4
        pos_hint: {'center_x': 0.5, 'center_y': 0.55}
        spacing: dp(16)
        padding: dp(20)

        Label:
            text: 'Authentication Error'
            font_size: sp(20)
            bold: True
            color: 0.9, 0.3, 0.3, 1
            size_hint_y: None
            height: dp(36)

        Label:
            id: error_label
            text: root.error_message
            font_size: sp(13)
            color: 0.8, 0.8, 0.8, 1
            text_size: self.width, None
            halign: 'center'

        Label:
            text: 'Set FALCON_CLIENT_ID and FALCON_CLIENT_SECRET\nthen restart the application.'
            font_size: sp(12)
            color: 0.6, 0.6, 0.6, 1
            halign: 'center'
            text_size: self.width, None

<DetailScreen>:
    name: 'detail'
    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            size_hint_y: None
            height: dp(56)
            padding: [dp(12), dp(8)]
            spacing: dp(12)
            canvas.before:
                Color:
                    rgba: 0.13, 0.13, 0.16, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            Button:
                text: '← Back'
                size_hint_x: None
                width: dp(100)
                on_press: app.go_back()
                background_color: 0.25, 0.25, 0.35, 1
                background_normal: ''

            Label:
                id: detail_title
                text: root.event_title
                font_size: sp(15)
                bold: True
                color: 0.9, 0.9, 0.9, 1
                halign: 'left'
                text_size: self.width, None

        ScrollView:
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                padding: dp(16)
                spacing: dp(12)

                Label:
                    id: detail_type
                    text: root.event_type_text
                    font_size: sp(12)
                    color: 0.4, 0.85, 0.6, 1
                    size_hint_y: None
                    height: dp(20)
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    id: detail_ts
                    text: root.event_ts_text
                    font_size: sp(12)
                    color: 0.55, 0.55, 0.55, 1
                    size_hint_y: None
                    height: dp(20)
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    id: detail_confidence
                    text: root.event_confidence_text
                    font_size: sp(12)
                    color: 0.9, 0.9, 0.9, 1
                    size_hint_y: None
                    height: dp(20)
                    halign: 'left'
                    text_size: self.width, None

                BoxLayout:
                    size_hint_y: None
                    height: dp(2)
                    canvas.before:
                        Color:
                            rgba: 0.25, 0.25, 0.3, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

                Label:
                    text: 'Description'
                    font_size: sp(13)
                    bold: True
                    color: 0.7, 0.7, 0.7, 1
                    size_hint_y: None
                    height: dp(24)
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    id: detail_desc
                    text: root.event_desc_text
                    font_size: sp(13)
                    color: 0.85, 0.85, 0.85, 1
                    size_hint_y: None
                    height: self.texture_size[1]
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    text: 'Indicators'
                    font_size: sp(13)
                    bold: True
                    color: 0.7, 0.7, 0.7, 1
                    size_hint_y: None
                    height: dp(24)
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    id: detail_indicators
                    text: root.event_indicators_text
                    font_size: sp(12)
                    color: 0.75, 0.85, 0.75, 1
                    size_hint_y: None
                    height: self.texture_size[1]
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    text: 'Source Rule'
                    font_size: sp(13)
                    bold: True
                    color: 0.7, 0.7, 0.7, 1
                    size_hint_y: None
                    height: dp(24)
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    id: detail_rule
                    text: root.event_rule_text
                    font_size: sp(12)
                    color: 0.65, 0.7, 0.9, 1
                    size_hint_y: None
                    height: self.texture_size[1]
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    text: 'Raw Fields'
                    font_size: sp(13)
                    bold: True
                    color: 0.7, 0.7, 0.7, 1
                    size_hint_y: None
                    height: dp(24)
                    halign: 'left'
                    text_size: self.width, None

                Label:
                    id: detail_raw
                    text: root.event_raw_text
                    font_size: sp(11)
                    color: 0.6, 0.6, 0.6, 1
                    size_hint_y: None
                    height: self.texture_size[1]
                    halign: 'left'
                    text_size: self.width, None
"""

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class EventRecord:
    """Holds data for a single TailoredIntelligence event."""

    def __init__(self, raw: dict):
        """Initialise from the raw API response dict for one event."""
        self.id: str = raw.get("id", "")
        # The event type field name varies; check several common names.
        self.event_type: str = (
            raw.get("type")
            or raw.get("event_type")
            or raw.get("source_type")
            or "Unknown"
        )
        # Headline / title of the event.
        # The real TailoredIntelligence API stores content in the 'body' field.
        # When title/headline/name are absent, body may be JSON — extract a
        # readable single-line summary rather than dumping raw JSON.
        _body = raw.get("body", "")
        self.headline: str = (
            raw.get("title")
            or raw.get("headline")
            or raw.get("name")
            or raw.get("summary", "")
            or _extract_headline_from_body(_body)
            or "(no title)"
        )
        # Confidence value as a string (e.g. "high", "medium", "low", or numeric).
        confidence_raw = raw.get("confidence") or raw.get("confidence_level") or ""
        self.confidence: str = str(confidence_raw) if confidence_raw else "Unknown"
        # Timestamps.
        ts = (
            raw.get("created_date") or raw.get("updated_date") or raw.get("created_timestamp") or ""
        )
        self.timestamp: str = _format_ts(ts)
        self.timestamp_raw: str = str(ts)
        # Description.
        self.description: str = (
            raw.get("description")
            or raw.get("body")
            or ""
        )
        # Indicators — may be a list of strings or dicts.
        self.indicators: list = raw.get("indicators") or raw.get("iocs") or []
        # Source rule ID — the real API stores this in matched_rules[0]["rule_id"].
        matched = raw.get("matched_rules") or []
        self.rule_id: str = (
            (matched[0].get("rule_id", "") if matched else "")
            or raw.get("rule_id")
            or raw.get("source_rule_id")
            or ""
        )
        # Full raw dict for the detail view.
        self._raw: dict = raw

    def confidence_color(self) -> list:
        """Return an RGBA list colour-coded by confidence string."""
        conf = self.confidence.lower()
        if conf in ("high", "critical"):
            return [0.9, 0.3, 0.3, 1]
        if conf in ("medium", "moderate"):
            return [0.9, 0.6, 0.2, 1]
        if conf in ("low", "informational"):
            return [0.4, 0.8, 0.4, 1]
        return [0.6, 0.6, 0.6, 1]

    def card_bg_color(self) -> list:
        """Return a subtle background colour for the event card."""
        return [0.12, 0.13, 0.17, 1]


class RuleRecord:
    """Holds data for a single TailoredIntelligence rule."""

    def __init__(self, raw: dict):
        """Initialise from the raw API response dict for one rule."""
        self.id: str = raw.get("id", "")
        self.name: str = raw.get("name") or raw.get("value") or "(unnamed)"
        self.rule_type: str = raw.get("rule_type") or raw.get("type") or "Unknown"
        enabled_raw = raw.get("enabled")
        # Treat truthy value as enabled; absent field treated as unknown.
        if enabled_raw is None:
            self.enabled: Optional[bool] = None
        else:
            self.enabled = bool(enabled_raw)
        self._raw: dict = raw

    def status_text(self) -> str:
        """Return a human-readable status string."""
        if self.enabled is None:
            return "Unknown"
        return "Enabled" if self.enabled else "Disabled"

    def status_color(self) -> list:
        """Return RGBA colour for the status label."""
        if self.enabled is None:
            return [0.55, 0.55, 0.55, 1]
        if self.enabled:
            return [0.3, 0.85, 0.4, 1]
        return [0.7, 0.3, 0.3, 1]


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------

def _format_ts(raw_ts: str) -> str:
    """Normalise an ISO8601 timestamp to 'YYYY-MM-DD HH:MM' or return as-is."""
    if not raw_ts:
        return ""
    try:
        # Handle numeric epoch seconds or milliseconds.
        if isinstance(raw_ts, (int, float)):
            ts_val = float(raw_ts)
            if ts_val > 1e10:
                ts_val /= 1000  # milliseconds → seconds
            dt = datetime.utcfromtimestamp(ts_val)
            return dt.strftime("%Y-%m-%d %H:%M")
        # ISO8601 string; strip trailing Z or +offset.
        clean = str(raw_ts)[:19].replace("T", " ")
        return clean
    except (ValueError, OSError):
        return str(raw_ts)[:19]


def _confidence_display(value: str) -> str:
    """Return a display string for a confidence value."""
    if not value or value.lower() == "unknown":
        return "Unknown"
    return value.capitalize()


def _format_indicators(indicators: list) -> str:
    """Format a list of indicators as a multi-line string."""
    if not indicators:
        return "(none)"
    lines = []
    for ind in indicators[:20]:  # cap at 20 to avoid overwhelming the UI
        if isinstance(ind, dict):
            # Extract common indicator fields.
            itype = ind.get("type") or ind.get("indicator_type") or "?"
            value = ind.get("value") or ind.get("indicator") or str(ind)
            lines.append(f"  [{itype}] {value}")
        else:
            lines.append(f"  {ind}")
    if len(indicators) > 20:
        lines.append(f"  … and {len(indicators) - 20} more")
    return "\n".join(lines)


def _format_raw(raw: dict, max_entries: int = 30) -> str:
    """Format a dict as readable key: value lines, capped at max_entries."""
    lines = []
    for i, (k, v) in enumerate(raw.items()):
        if i >= max_entries:
            lines.append(f"  … ({len(raw) - max_entries} more fields)")
            break
        display_v = str(v)
        if len(display_v) > 120:
            display_v = display_v[:120] + "…"
        lines.append(f"  {k}: {display_v}")
    return "\n".join(lines)


def _parse_body_flexible(text: str) -> Optional[dict]:
    """Attempt to parse *text* as structured data, tolerating common non-JSON formats.

    Tries in order:
      1. Standard JSON (json.loads).
      2. Lua-table notation — ``["key"] = value`` — converted to JSON-like form.
      3. Regex heuristic: extract ``key = value`` or ``"key": value`` pairs.

    Returns a dict if any method succeeds, or ``None`` if the text is not
    parseable as a key-value structure.  Callers should treat the raw string as
    plain text when ``None`` is returned.
    """
    import re  # pylint: disable=import-outside-toplevel

    if not text:
        return None
    stripped = text.strip()

    # ── Pass 1: standard JSON ────────────────────────────────────────────────
    if stripped[:1] in ("{", "[", '"'):
        try:
            result = json.loads(stripped)
            if isinstance(result, dict):
                return result
            return None  # arrays / scalars handled by callers directly
        except (json.JSONDecodeError, ValueError):
            pass

    # Only attempt further parsing if the text looks like a table/struct.
    if stripped[:1] != "{":
        return None

    # ── Pass 2: Lua-table / annotated-JSON heuristic ─────────────────────────
    # Lua tables use  ["key"] = value  instead of  "key": value.
    # Also handles JS-style  key: value  (unquoted keys).
    # Steps:
    #   a) ["key"] = value  →  "key": value
    #   b) key = value  (bare identifier)  →  "key": value
    #   c) Remove trailing commas before } or ]
    #   d) Convert Lua true/false/nil → JSON true/false/null
    lua = stripped
    # a) ["key"] = expr  →  "key": expr
    lua = re.sub(r'\["([^"]+)"\]\s*=\s*', r'"\1": ', lua)
    # b) bare_key = expr  (only if looks like identifier, not already a string)
    lua = re.sub(r'(?<!["\w])([A-Za-z_][A-Za-z0-9_.]*)\s*=\s*(?!")', r'"\1": ', lua)
    # c) trailing commas before closing brackets
    lua = re.sub(r',\s*([}\]])', r'\1', lua)
    # d) Lua literals
    lua = re.sub(r'\btrue\b', 'true', lua)
    lua = re.sub(r'\bfalse\b', 'false', lua)
    lua = re.sub(r'\bnil\b', 'null', lua)

    try:
        result = json.loads(lua)
        if isinstance(result, dict):
            return result
    except (json.JSONDecodeError, ValueError):
        pass

    # ── Pass 3: pure regex extraction ────────────────────────────────────────
    # Extract all  "key": value  or  key = value  pairs from the raw text.
    pairs: dict = {}
    # Pattern A: quoted key, colon, value (JSON-like)
    for m in re.finditer(r'"([^"]+)"\s*[:=]\s*("(?:[^"\\]|\\.)*"|\d[\d.]*|true|false|null|\[[^\]]*\])', stripped):
        k = m.group(1)
        v_raw = m.group(2)
        try:
            pairs[k] = json.loads(v_raw)
        except (json.JSONDecodeError, ValueError):
            pairs[k] = v_raw.strip('"')
    # Pattern B: bare key = value (Lua-style, e.g. motd.enable = true)
    for m in re.finditer(r'([A-Za-z_][A-Za-z0-9_.]*)\s*=\s*("(?:[^"\\]|\\.)*"|\d[\d.]*|true|false|nil)', stripped):
        k = m.group(1)
        v_raw = m.group(2).replace("nil", "null")
        try:
            pairs[k] = json.loads(v_raw)
        except (json.JSONDecodeError, ValueError):
            pairs[k] = v_raw.strip('"')

    return pairs if pairs else None


def _extract_headline_from_body(body: str) -> str:
    """Return a short, readable headline extracted from a body string.

    When the TailoredIntelligence API returns content only in the *body* field
    and that field is JSON (or Lua-table / malformed JSON), using the raw string
    as a card headline produces an unreadable wall of braces.  This function
    extracts a meaningful single-line summary instead:

    - Plain text → returned as-is (truncated to 200 chars).
    - JSON object / Lua-table / key-value struct → looks for common title-like
      keys first (title, name, headline, subject, summary, message, text, type);
      falls back to the first non-empty string scalar value found; last resort
      is a compact key list.
    - JSON array → first element summarised; count appended if >1.
    - Other JSON scalars → converted to string.
    - Unparseable non-plain text → returned as-is (truncated).
    """
    if not body:
        return ""
    stripped = body.strip()
    if stripped[:1] not in ("{", "[", '"'):
        return body[:200]

    # Try standard JSON first; fall back to flexible parser for Lua/malformed.
    parsed = None
    try:
        parsed = json.loads(stripped)
    except (json.JSONDecodeError, ValueError):
        if stripped[:1] == "{":
            parsed = _parse_body_flexible(stripped)

    if parsed is None:
        return body[:200]

    if isinstance(parsed, dict):
        # Priority keys that are likely to contain a human-readable title.
        for key in ("title", "name", "headline", "subject", "summary", "message", "text", "type"):
            val = parsed.get(key)
            if isinstance(val, str) and val.strip():
                return val[:200]
        # Fall back to first non-empty string scalar in the dict.
        for val in parsed.values():
            if isinstance(val, str) and val.strip():
                return val[:200]
        # Non-string scalars (bool, int, float): format as "key: value" pairs so
        # the user sees the actual content, not just key names.
        scalar_pairs = [
            f"{k}: {str(v).lower() if isinstance(v, bool) else v}"
            for k, v in parsed.items()
            if isinstance(v, (bool, int, float))
        ]
        if scalar_pairs:
            summary = "  |  ".join(scalar_pairs[:4])
            if len(scalar_pairs) > 4:
                summary += f" (+{len(scalar_pairs) - 4} more)"
            return summary[:200]
        # Last resort: list the top-level keys so the card shows something useful.
        keys = list(parsed.keys())[:6]
        suffix = ", …" if len(parsed) > 6 else ""
        return "{" + ", ".join(keys) + suffix + "}"
    if isinstance(parsed, list):
        if not parsed:
            return "(empty)"
        first = parsed[0]
        summary = (
            _extract_headline_from_body(json.dumps(first))
            if isinstance(first, (dict, list)) else str(first)
        )
        if len(parsed) > 1:
            summary += f" (+{len(parsed) - 1} more)"
        return summary[:200]
    # Scalar JSON value.
    return str(parsed)[:200] if parsed is not None else ""


def _format_card_summary(raw: dict) -> str:
    """Build a compact key-value summary line for the EventCard.

    Accepts the raw API response dict for one event.  Extracts the most
    informative fields from top-level keys and the (possibly JSON-encoded)
    body so the user can read key details without drilling into the detail
    screen.

    Returns a single-line string like:
        "severity: high  |  tags: phishing, cred  |  rule: APT-123"
    """
    parts = []

    # Severity / confidence already shown in confidence row — skip duplication.
    # Try to extract structured fields from the raw body if it is JSON.
    body = raw.get("body", "")
    body_data: dict = {}
    if body and body.strip()[:1] in ("{", "["):
        try:
            parsed = json.loads(body)
            if isinstance(parsed, dict):
                body_data = parsed
        except (json.JSONDecodeError, ValueError):
            # Try flexible parser for Lua tables / malformed JSON.
            flexible = _parse_body_flexible(body)
            if isinstance(flexible, dict):
                body_data = flexible

    # severity
    severity = (
        body_data.get("severity")
        or body_data.get("severity_name")
        or raw.get("severity")
        or ""
    )
    if severity:
        parts.append(f"severity: {str(severity).lower()}")

    # tags / labels
    tags = (
        body_data.get("tags")
        or body_data.get("labels")
        or raw.get("tags")
        or []
    )
    if isinstance(tags, list) and tags:
        tag_str = ", ".join(str(t) for t in tags[:4])
        if len(tags) > 4:
            tag_str += f" +{len(tags) - 4}"
        parts.append(f"tags: {tag_str}")
    elif isinstance(tags, str) and tags:
        parts.append(f"tags: {tags}")

    # indicators / IOCs
    iocs = (
        body_data.get("indicators")
        or body_data.get("iocs")
        or raw.get("indicators")
        or raw.get("iocs")
        or []
    )
    if isinstance(iocs, list) and iocs:
        first_ioc = iocs[0]
        if isinstance(first_ioc, dict):
            first_ioc = first_ioc.get("value") or first_ioc.get("indicator") or str(first_ioc)
        ioc_str = str(first_ioc)
        if len(iocs) > 1:
            ioc_str += f" +{len(iocs) - 1}"
        parts.append(f"ioc: {ioc_str}")

    # matched rule (top-level matched_rules takes priority)
    matched = raw.get("matched_rules") or []
    rule_id = (matched[0].get("rule_id", "") if matched else "") or raw.get("rule_id") or ""
    if rule_id:
        parts.append(f"rule: {rule_id}")
    else:
        rule_name = (
            body_data.get("rule_name")
            or body_data.get("matched_rule")
            or body_data.get("rule")
            or ""
        )
        if rule_name:
            parts.append(f"rule: {str(rule_name)[:40]}")

    # actor / threat group
    actor = (
        body_data.get("actor")
        or body_data.get("threat_actor")
        or body_data.get("actor_name")
        or raw.get("actor")
        or ""
    )
    if actor:
        parts.append(f"actor: {str(actor)}")

    if not parts:
        # Fall back: list the top-level body keys as a breadcrumb
        if body_data:
            keys = list(body_data.keys())[:5]
            parts.append("fields: " + ", ".join(keys))
        else:
            return ""

    return "  |  ".join(parts)[:160]


def _format_description(raw_description: str) -> str:
    """Return a human-readable version of an event description.

    The TailoredIntelligence API sometimes returns the description field as a
    JSON-encoded string (or Lua-table / other malformed JSON) rather than plain
    prose.  This function attempts to decode it and render the contents as
    clearly labelled lines.

    Rendering rules:
    - Plain text (non-JSON) → returned unchanged.
    - JSON object / Lua-table / key-value struct → each top-level key rendered
      as "  Label: value".  Nested dicts are flattened one level; nested lists
      are joined with ", ".
    - JSON array (list) → each element rendered as a numbered bullet.
    - Any other JSON scalar → converted to string and returned.
    - Malformed / unparseable struct-like text → formatted as raw text block.
    """
    if not raw_description:
        return "(no description)"

    # Try to detect and parse JSON.  A description that doesn't start with
    # '{' or '[' is almost certainly plain text — skip the parse attempt.
    stripped = raw_description.strip()
    if stripped[:1] not in ("{", "[", '"'):
        return raw_description

    # Pass 1: standard JSON.
    parsed = None
    try:
        parsed = json.loads(stripped)
    except (json.JSONDecodeError, ValueError):
        # Pass 2: flexible parser for Lua tables / malformed JSON.
        if stripped[:1] == "{":
            parsed = _parse_body_flexible(stripped)

    if parsed is None:
        # Still not parseable — present as a formatted raw text block so at
        # least the content is legible rather than being raw JSON noise.
        return f"[raw]\n{raw_description}"

    if isinstance(parsed, dict):
        return _render_desc_dict(parsed)
    if isinstance(parsed, list):
        return _render_desc_list(parsed)
    # Scalar JSON value (string, number, bool, null).
    return str(parsed) if parsed is not None else "(no description)"


def _render_desc_dict(data: dict, indent: str = "  ") -> str:
    """Render a dict as labelled lines, one key per line.

    Keys are title-cased with underscores replaced by spaces for readability.
    Values that are themselves dicts are indented one further level.  List
    values are joined with '; ' to stay on a single line unless the list
    contains dicts (rendered as sub-bullets).
    """
    lines = []
    for key, value in data.items():
        label = key.replace("_", " ").replace("-", " ").title()
        if isinstance(value, dict):
            lines.append(f"{indent}{label}:")
            for sub_k, sub_v in value.items():
                sub_label = sub_k.replace("_", " ").replace("-", " ").title()
                lines.append(f"{indent}  {sub_label}: {sub_v}")
        elif isinstance(value, list):
            if not value:
                lines.append(f"{indent}{label}: (none)")
            elif all(isinstance(v, dict) for v in value):
                lines.append(f"{indent}{label}:")
                for item in value[:10]:
                    # Render each list-of-dicts item as a compact bullet.
                    parts = [f"{k}: {v}" for k, v in item.items()]
                    lines.append(f"{indent}  • {', '.join(parts)}")
                if len(value) > 10:
                    lines.append(f"{indent}  … and {len(value) - 10} more")
            else:
                joined = "; ".join(str(v) for v in value[:20])
                if len(value) > 20:
                    joined += f"; … (+{len(value) - 20})"
                lines.append(f"{indent}{label}: {joined}")
        elif value is None:
            lines.append(f"{indent}{label}: —")
        else:
            display = str(value)
            if len(display) > 200:
                display = display[:200] + "…"
            lines.append(f"{indent}{label}: {display}")
    return "\n".join(lines) if lines else "(no description)"


def _render_desc_list(items: list) -> str:
    """Render a JSON array as a numbered list of items."""
    if not items:
        return "(empty)"
    lines = []
    for i, item in enumerate(items[:30], start=1):
        if isinstance(item, dict):
            # Compact single-line representation of each dict item.
            parts = [f"{k}: {v}" for k, v in item.items()]
            lines.append(f"  {i}. {', '.join(parts)}")
        else:
            lines.append(f"  {i}. {item}")
    if len(items) > 30:
        lines.append(f"  … and {len(items) - 30} more")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# FalconPy client wrapper
# ---------------------------------------------------------------------------

class TailoredIntelClient:
    """Thin wrapper around the FalconPy TailoredIntelligence service class."""

    # Maximum IDs per batch GET request.
    _BATCH_SIZE = 100

    def __init__(self):
        """Construct without authenticating — call connect() first."""
        self._sdk: Optional[TailoredIntelligence] = None
        self.status: str = "disconnected"
        self.error: str = ""

    def connect(
        self,
        client_id_override: str = "",
        client_secret_override: str = "", # nosec - Bandit FP
    ) -> bool:
        """Authenticate using provided credentials or env vars.

        Credential resolution order (first non-empty value wins):
          1. *client_id_override* / *client_secret_override* (CLI args)
          2. FALCON_CLIENT_ID / FALCON_CLIENT_SECRET environment variables

        Returns True on success, False on failure.  Sets self.error on failure.
        """
        client_id = client_id_override or os.environ.get("FALCON_CLIENT_ID", "")
        client_secret = client_secret_override or os.environ.get("FALCON_CLIENT_SECRET", "")
        if not client_id or not client_secret:
            self.error = (
                "Credentials not provided. Supply -k/-s arguments or set "
                "FALCON_CLIENT_ID / FALCON_CLIENT_SECRET environment variables."
            )
            self.status = "error"
            return False
        try:
            sdk = TailoredIntelligence(
                client_id=client_id, client_secret=client_secret
            )
            if not sdk.token_valid:
                self.error = (
                    f"Authentication failed: {sdk.token_fail_reason}"
                )
                self.status = "error"
                return False
            self._sdk = sdk
            self.status = "connected"
            self.error = ""
            return True
        except Exception as exc:  # pylint: disable=broad-except
            self.error = str(exc)
            self.status = "error"
            return False

    def fetch_events(
        self,
        fql_filter: str = "",
        limit: int = 200,
    ) -> list:
        """Return a list of EventRecord objects matching the optional FQL filter.

        Paginates via offset until *limit* events are collected or results are
        exhausted.
        """
        if self._sdk is None:
            return []

        # Collect event IDs via query_events.
        all_ids: list[str] = []
        offset = 0
        page_size = min(100, limit)

        while len(all_ids) < limit:
            kwargs: dict = {"limit": page_size, "offset": offset}
            if fql_filter:
                kwargs["filter"] = fql_filter

            resp = self._sdk.query_events(**kwargs)
            if resp.get("status_code", 0) not in (200, 201):
                break

            body = resp.get("body", {})
            ids_page: list = body.get("resources", [])
            if not ids_page:
                break

            all_ids.extend(ids_page)
            total = body.get("meta", {}).get("pagination", {}).get("total", 0)
            offset += len(ids_page)

            if offset >= total or len(all_ids) >= limit:
                break

        if not all_ids:
            return []

        # Fetch event entities in batches.
        records: list[EventRecord] = []
        for i in range(0, len(all_ids), self._BATCH_SIZE):
            batch = all_ids[i : i + self._BATCH_SIZE]
            resp = self._sdk.get_event_entities(ids=batch)
            if resp.get("status_code", 0) not in (200, 201):
                continue
            for raw in resp.get("body", {}).get("resources", []):
                records.append(EventRecord(raw))

        return records

    def fetch_rules(self, limit: int = 200) -> list:
        """Return a list of RuleRecord objects for active tailored intelligence rules.

        Paginates via offset until *limit* rules are collected or results are
        exhausted.
        """
        if self._sdk is None:
            return []

        all_ids: list[str] = []
        offset = 0
        page_size = min(100, limit)

        while len(all_ids) < limit:
            resp = self._sdk.query_rules(limit=page_size, offset=offset)
            if resp.get("status_code", 0) not in (200, 201):
                break

            body = resp.get("body", {})
            ids_page: list = body.get("resources", [])
            if not ids_page:
                break

            all_ids.extend(ids_page)
            total = body.get("meta", {}).get("pagination", {}).get("total", 0)
            offset += len(ids_page)

            if offset >= total or len(all_ids) >= limit:
                break

        if not all_ids:
            return []

        records: list[RuleRecord] = []
        for i in range(0, len(all_ids), self._BATCH_SIZE):
            batch = all_ids[i : i + self._BATCH_SIZE]
            resp = self._sdk.get_rule_entities(ids=batch)
            if resp.get("status_code", 0) not in (200, 201):
                continue
            for raw in resp.get("body", {}).get("resources", []):
                records.append(RuleRecord(raw))

        return records


# ---------------------------------------------------------------------------
# Kivy widget classes
# ---------------------------------------------------------------------------

class RootLayout(BoxLayout):
    """Top-level vertical layout containing all application UI zones."""


class TopBar(BoxLayout):
    """Fixed-height header with app title, connection status, and refresh button."""


class TabBar(BoxLayout):
    """Horizontal tab bar for switching between Events and Rules views."""


class TabButton(Widget):
    """Single tab button (inactive state)."""


class EventCard(RecycleDataViewBehavior, BoxLayout):
    """One row in the event RecycleView — displays type, headline, confidence."""

    index = NumericProperty(0)
    event_id = StringProperty("")
    event_type = StringProperty("")
    headline = StringProperty("")
    card_summary = StringProperty("")
    confidence = StringProperty("")
    timestamp = StringProperty("")
    bg_color = ListProperty([0.12, 0.13, 0.17, 1])
    confidence_color = ListProperty([0.6, 0.6, 0.6, 1])

    def refresh_view_attrs(self, rv, index, data):
        """Called by RecycleView to bind data to this widget instance."""
        self.index = index
        return super().refresh_view_attrs(rv, index, data)

    def on_touch_down(self, touch):
        """Detect a tap on this card and open the event detail screen."""
        if self.collide_point(*touch.pos):
            App.get_running_app().open_event_detail(self.event_id)
            return True
        return super().on_touch_down(touch)


class EventsRecycleView(RecycleView):
    """Virtualised scrollable list of EventCard widgets."""


class FilterBar(BoxLayout):
    """Date-range filter buttons and event count label above the event feed."""


class PaginationBar(BoxLayout):
    """Prev/Next navigation, page info label, and per-page size buttons."""


class RuleCard(RecycleDataViewBehavior, BoxLayout):
    """One row in the rules RecycleView — displays name, type, enabled state."""

    index = NumericProperty(0)
    rule_name = StringProperty("")
    rule_type = StringProperty("")
    rule_status = StringProperty("")
    rule_id = StringProperty("")
    rule_status_color = ListProperty([0.6, 0.6, 0.6, 1])

    def refresh_view_attrs(self, rv, index, data):
        """Called by RecycleView to bind data to this widget instance."""
        self.index = index
        return super().refresh_view_attrs(rv, index, data)


class RulesRecycleView(RecycleView):
    """Virtualised scrollable list of RuleCard widgets."""


class LoadingOverlay(FloatLayout):
    """Semi-transparent overlay displayed while data is loading."""

    def on_touch_down(self, touch):
        """Pass all touches through when overlay is disabled (hidden)."""
        if self.disabled:
            return False
        return super().on_touch_down(touch)


class ErrorOverlay(FloatLayout):
    """Full-screen error overlay shown when authentication fails."""

    error_message = StringProperty("")

    def on_touch_down(self, touch):
        """Pass all touches through when overlay is disabled (hidden)."""
        if self.disabled:
            return False
        return super().on_touch_down(touch)


class DetailScreen(Screen):
    """Full-screen detail view for a single event."""

    event_title = StringProperty("")
    event_type_text = StringProperty("")
    event_ts_text = StringProperty("")
    event_confidence_text = StringProperty("")
    event_desc_text = StringProperty("")
    event_indicators_text = StringProperty("")
    event_rule_text = StringProperty("")
    event_raw_text = StringProperty("")


# ---------------------------------------------------------------------------
# Application state
# ---------------------------------------------------------------------------

class AppState:
    """Mutable application state shared between the UI thread and worker threads."""

    def __init__(self):
        """Initialise state fields to safe defaults."""
        self.lock = threading.Lock()
        self.events: list[EventRecord] = []
        self.rules: list[RuleRecord] = []
        # Map event_id → EventRecord for O(1) detail look-up.
        self.events_by_id: dict[str, EventRecord] = {}
        # Map rule_id → RuleRecord for detail cross-reference.
        self.rules_by_id: dict[str, RuleRecord] = {}
        self.loading: bool = False
        self.error_message: str = ""
        # Active date-range selection: '24h', '7d', '30d', 'all'.
        self.date_range: str = "24h"
        # Pagination state for the events list.
        self.current_page: int = 0
        self.page_size: int = 50


# ---------------------------------------------------------------------------
# Main application
# ---------------------------------------------------------------------------

class TailoredIntelBrowserApp(App):
    """Kivy application for browsing CrowdStrike Tailored Intelligence events."""

    # Build the app title.
    title = "Tailored Intel Browser"

    # Current tab ('events' or 'rules').
    _active_tab = "events"

    def __init__(self, client_id: str = "", client_secret: str = "", **kwargs): # nosec - Bandit FP
        """Initialise the app and its supporting components.

        *client_id* and *client_secret* may be provided from CLI args.  When
        non-empty they take precedence over environment variables during
        authentication.
        """
        super().__init__(**kwargs)
        # Store CLI-provided credentials for use in on_start().
        self._cli_client_id: str = client_id
        self._cli_client_secret: str = client_secret
        self.client = TailoredIntelClient()
        self.state = AppState()
        # References to key widgets populated in build().
        self._events_rv: Optional[EventsRecycleView] = None
        self._rules_rv: Optional[RulesRecycleView] = None
        self._loading_overlay: Optional[LoadingOverlay] = None
        self._error_overlay: Optional[ErrorOverlay] = None
        self._status_label = None
        self._event_count_label = None
        self._pagination_bar: Optional[PaginationBar] = None
        self._screen_manager: Optional[ScreenManager] = None
        self._detail_screen: Optional[DetailScreen] = None
        self._main_screen_widget = None

    # ------------------------------------------------------------------
    # Kivy lifecycle
    # ------------------------------------------------------------------

    def build(self):
        """Build and return the root widget tree."""
        Builder.load_string(KV)

        # ---- Root screen manager allows switching between list and detail ----
        self._screen_manager = ScreenManager()

        # ---- Main (list) screen ----
        main_screen = Screen(name="main")
        root = RootLayout()

        top_bar = TopBar()
        self._status_label = top_bar.ids.status_label
        # Wire refresh button.
        top_bar.ids.refresh_btn.bind(on_press=lambda _: self.on_refresh_pressed())
        root.add_widget(top_bar)

        # Tab bar.
        tab_bar = TabBar()
        btn_events = self._make_tab_button("Events", active=True)
        btn_rules = self._make_tab_button("Rules", active=False)
        btn_events.bind(on_press=lambda _: self._switch_tab("events"))
        btn_rules.bind(on_press=lambda _: self._switch_tab("rules"))
        self._tab_btn_events = btn_events
        self._tab_btn_rules = btn_rules
        tab_bar.add_widget(btn_events)
        tab_bar.add_widget(btn_rules)
        root.add_widget(tab_bar)

        # Filter bar (only visible on events tab).
        self._filter_bar = FilterBar()
        self._event_count_label = self._filter_bar.ids.event_count_label
        root.add_widget(self._filter_bar)

        # Pagination bar (only visible on events tab).
        self._pagination_bar = PaginationBar()
        root.add_widget(self._pagination_bar)

        # Events RecycleView.
        self._events_rv = EventsRecycleView()
        self._events_rv.data = []
        self._events_container = self._events_rv

        # Rules RecycleView.
        self._rules_rv = RulesRecycleView()
        self._rules_rv.data = []

        # Content area swaps between events and rules views.
        self._content_area = BoxLayout()
        self._content_area.add_widget(self._events_rv)
        root.add_widget(self._content_area)

        # ---- Overlays (stacked via FloatLayout) ----
        self._loading_overlay = LoadingOverlay()
        self._error_overlay = ErrorOverlay()
        self._error_overlay.opacity = 0
        self._error_overlay.disabled = True

        # Wrap root in a FloatLayout to layer the overlays.
        float_root = FloatLayout()
        float_root.add_widget(root)
        float_root.add_widget(self._loading_overlay)
        float_root.add_widget(self._error_overlay)
        self._loading_overlay.opacity = 0
        self._loading_overlay.disabled = True

        main_screen.add_widget(float_root)
        self._screen_manager.add_widget(main_screen)

        # ---- Detail screen ----
        self._detail_screen = DetailScreen()
        self._screen_manager.add_widget(self._detail_screen)

        return self._screen_manager

    def _make_tab_button(self, text: str, active: bool):
        """Create a styled tab Button widget."""
        from kivy.uix.button import Button
        from kivy.metrics import dp
        btn = Button(
            text=text,
            size_hint_x=None,
            width=dp(120),
            size_hint_y=None,
            height=dp(36),
            background_normal="",
            background_color=(0.2, 0.4, 0.8, 1) if active else (0.15, 0.15, 0.2, 1),
            color=(1, 1, 1, 1) if active else (0.7, 0.7, 0.7, 1),
            font_size="13sp",
        )
        return btn

    def on_start(self):
        """Called after build() — authenticate in background then load data."""
        self._set_status("connecting")

        def _auth_worker():
            ok = self.client.connect(
                client_id_override=self._cli_client_id,
                client_secret_override=self._cli_client_secret,
            )
            Clock.schedule_once(lambda dt: self._on_connect_done(ok), 0)

        threading.Thread(target=_auth_worker, daemon=True).start()

    def _on_connect_done(self, ok: bool):
        """Called on main thread after background auth completes."""
        if ok:
            self._set_status("connected")
            self._load_data()
        else:
            self._set_status("error")
            self._show_error(self.client.error)

    # ------------------------------------------------------------------
    # Tab switching
    # ------------------------------------------------------------------

    def _switch_tab(self, tab: str):
        """Switch the content area between 'events' and 'rules' views."""
        self._active_tab = tab
        self._content_area.clear_widgets()

        if tab == "events":
            self._content_area.add_widget(self._events_rv)
            self._filter_bar.opacity = 1
            self._filter_bar.disabled = False
            self._pagination_bar.opacity = 1
            self._pagination_bar.disabled = False
            self._tab_btn_events.background_color = (0.2, 0.4, 0.8, 1)
            self._tab_btn_events.color = (1, 1, 1, 1)
            self._tab_btn_rules.background_color = (0.15, 0.15, 0.2, 1)
            self._tab_btn_rules.color = (0.7, 0.7, 0.7, 1)
        else:
            self._content_area.add_widget(self._rules_rv)
            self._filter_bar.opacity = 0
            self._filter_bar.disabled = True
            self._pagination_bar.opacity = 0
            self._pagination_bar.disabled = True
            self._tab_btn_rules.background_color = (0.2, 0.4, 0.8, 1)
            self._tab_btn_rules.color = (1, 1, 1, 1)
            self._tab_btn_events.background_color = (0.15, 0.15, 0.2, 1)
            self._tab_btn_events.color = (0.7, 0.7, 0.7, 1)
            # Load rules if not yet loaded.
            with self.state.lock:
                rules_loaded = bool(self.state.rules)
            if not rules_loaded:
                self._load_rules()

    # ------------------------------------------------------------------
    # Date range
    # ------------------------------------------------------------------

    def on_date_range_pressed(self, range_key: str):
        """Handle a date range button press — rebuild the FQL filter and reload."""
        with self.state.lock:
            self.state.date_range = range_key
            self.state.current_page = 0
        # Update button highlights.
        range_btns = {
            "24h": self._filter_bar.ids.range_24h,
            "7d": self._filter_bar.ids.range_7d,
            "30d": self._filter_bar.ids.range_30d,
            "all": self._filter_bar.ids.range_all,
        }
        for key, btn in range_btns.items():
            if key == range_key:
                btn.background_color = (0.2, 0.5, 0.2, 1)
            else:
                btn.background_color = (0.15, 0.15, 0.2, 1)
        self._load_events()

    def _build_fql_filter(self) -> str:
        """Construct an FQL filter string for the active date range.

        Returns an empty string when the range is 'all' (no filter).
        The TailoredIntelligence API supports FQL filtering on created_date.
        """
        with self.state.lock:
            range_key = self.state.date_range

        delta_map = {"24h": timedelta(hours=24), "7d": timedelta(days=7), "30d": timedelta(days=30)}
        delta = delta_map.get(range_key)
        if delta is None:
            return ""  # 'all' — no filter

        since = (datetime.utcnow() - delta).strftime("%Y-%m-%dT%H:%M:%SZ")
        return f"created_date:>='{since}'"

    # ------------------------------------------------------------------
    # Data loading
    # ------------------------------------------------------------------

    def on_refresh_pressed(self):
        """Handle the top-bar Refresh button."""
        self._load_data()

    def _load_data(self):
        """Trigger background loads for both events and rules."""
        self._load_events()

    def _load_events(self):
        """Load events in a background thread."""
        with self.state.lock:
            if self.state.loading:
                return
            self.state.loading = True
        self._show_loading(True)

        fql = self._build_fql_filter()

        def _worker():
            try:
                events = self.client.fetch_events(fql_filter=fql)
                # Sort newest-first.
                events.sort(key=lambda e: e.timestamp_raw, reverse=True)
                with self.state.lock:
                    self.state.events = events
                    self.state.events_by_id = {e.id: e for e in events}
                    self.state.error_message = ""
            except Exception as exc:  # pylint: disable=broad-except
                with self.state.lock:
                    self.state.error_message = str(exc)
            finally:
                with self.state.lock:
                    self.state.loading = False
                # Schedule UI update on the main thread.
                Clock.schedule_once(self._on_events_loaded, 0)

        threading.Thread(target=_worker, daemon=True).start()

    def _load_rules(self):
        """Load rules in a background thread."""
        def _worker():
            try:
                rules = self.client.fetch_rules()
                with self.state.lock:
                    self.state.rules = rules
                    self.state.rules_by_id = {r.id: r for r in rules}
            except Exception as exc:  # pylint: disable=broad-except
                with self.state.lock:
                    self.state.error_message = str(exc)
            finally:
                Clock.schedule_once(self._on_rules_loaded, 0)

        threading.Thread(target=_worker, daemon=True).start()

    # ------------------------------------------------------------------
    # UI update callbacks (always run on the main/Kivy thread)
    # ------------------------------------------------------------------

    def _on_events_loaded(self, _dt):
        """Called on the main thread after event loading completes."""
        self._show_loading(False)
        with self.state.lock:
            events = list(self.state.events)
            err = self.state.error_message
            self.state.current_page = 0

        if err:
            # Show error but keep any existing data visible.
            self._set_status("error")
            return

        self._set_status("connected")
        self._rebuild_events_list(events)

    def _on_rules_loaded(self, _dt):
        """Called on the main thread after rule loading completes."""
        with self.state.lock:
            rules = list(self.state.rules)
        self._rebuild_rules_list(rules)

    def _rebuild_events_list(self, events: list):
        """Repopulate the events RecycleView from a list of EventRecord objects.

        Applies client-side pagination using state.current_page and state.page_size.
        """
        with self.state.lock:
            page = self.state.current_page
            page_size = self.state.page_size

        total = len(events)
        import math  # pylint: disable=import-outside-toplevel
        total_pages = max(1, math.ceil(total / page_size))
        # Clamp page in case events shrank after a filter change.
        page = max(0, min(page, total_pages - 1))
        with self.state.lock:
            self.state.current_page = page

        start = page * page_size
        end = start + page_size
        page_events = events[start:end]

        data = []
        for ev in page_events:
            data.append(
                {
                    "event_id": ev.id,
                    "event_type": ev.event_type,
                    "headline": ev.headline,
                    "card_summary": _format_card_summary(ev._raw),  # pylint: disable=protected-access
                    "confidence": _confidence_display(ev.confidence),
                    "timestamp": ev.timestamp,
                    "bg_color": ev.card_bg_color(),
                    "confidence_color": ev.confidence_color(),
                }
            )
        self._events_rv.data = data

        # Update event count label.
        if self._event_count_label:
            self._event_count_label.text = f"{total} event{'s' if total != 1 else ''}"

        # Update pagination UI.
        self._update_pagination_ui(page, total_pages, total)

    def _update_pagination_ui(self, page: int, total_pages: int, total: int):
        """Refresh the pagination bar labels and button states."""
        if self._pagination_bar is None:
            return
        ids = self._pagination_bar.ids
        # Page info label.
        if total == 0:
            ids.page_info_label.text = "No events"
        else:
            ids.page_info_label.text = f"Page {page + 1} / {total_pages}"
        # Enable/disable Prev and Next.
        ids.prev_btn.disabled = page == 0
        ids.prev_btn.background_color = (
            (0.2, 0.4, 0.8, 1) if page > 0 else (0.1, 0.1, 0.15, 1)
        )
        ids.next_btn.disabled = page >= total_pages - 1
        ids.next_btn.background_color = (
            (0.2, 0.4, 0.8, 1) if page < total_pages - 1 else (0.1, 0.1, 0.15, 1)
        )
        # Highlight the active page size button.
        with self.state.lock:
            active_ps = self.state.page_size
        active_color = (0.2, 0.5, 0.2, 1)
        inactive_color = (0.15, 0.15, 0.2, 1)
        ids.ps_25.background_color = active_color if active_ps == 25 else inactive_color
        ids.ps_50.background_color = active_color if active_ps == 50 else inactive_color
        ids.ps_100.background_color = active_color if active_ps == 100 else inactive_color

    # ------------------------------------------------------------------
    # Pagination actions
    # ------------------------------------------------------------------

    def on_prev_page(self):
        """Navigate to the previous event page."""
        with self.state.lock:
            if self.state.current_page <= 0:
                return
            self.state.current_page -= 1
            events = list(self.state.events)
        self._rebuild_events_list(events)

    def on_next_page(self):
        """Navigate to the next event page."""
        with self.state.lock:
            events = list(self.state.events)
            page_size = self.state.page_size
        import math  # pylint: disable=import-outside-toplevel
        total_pages = max(1, math.ceil(len(events) / page_size))
        with self.state.lock:
            if self.state.current_page >= total_pages - 1:
                return
            self.state.current_page += 1
        self._rebuild_events_list(events)

    def on_page_size_change(self, size: int):
        """Change the number of events shown per page and reset to page 0."""
        with self.state.lock:
            self.state.page_size = size
            self.state.current_page = 0
            events = list(self.state.events)
        self._rebuild_events_list(events)

    def _rebuild_rules_list(self, rules: list):
        """Repopulate the rules RecycleView from a list of RuleRecord objects."""
        data = []
        for rule in rules:
            data.append(
                {
                    "rule_name": rule.name,
                    "rule_type": rule.rule_type,
                    "rule_status": rule.status_text(),
                    "rule_id": f"ID: {rule.id[:32]}…" if len(rule.id) > 32 else f"ID: {rule.id}",
                    "rule_status_color": rule.status_color(),
                }
            )
        self._rules_rv.data = data

    # ------------------------------------------------------------------
    # Detail screen
    # ------------------------------------------------------------------

    def open_event_detail(self, event_id: str):
        """Navigate to the detail screen for the given event ID."""
        with self.state.lock:
            ev = self.state.events_by_id.get(event_id)
            rules_by_id = dict(self.state.rules_by_id)

        if ev is None:
            return

        # Find the source rule, if any.
        rule_text = "(no source rule linked)"
        if ev.rule_id:
            rule = rules_by_id.get(ev.rule_id)
            if rule:
                rule_text = f"{rule.name} (type: {rule.rule_type}, {rule.status_text()})"
            else:
                rule_text = f"Rule ID: {ev.rule_id}"

        # Populate the detail screen properties.
        ds = self._detail_screen
        ds.event_title = ev.headline or "(no title)"
        ds.event_type_text = f"Type: {ev.event_type}"
        ds.event_ts_text = f"Timestamp: {ev.timestamp or '(unknown)'}"
        ds.event_confidence_text = f"Confidence: {_confidence_display(ev.confidence)}"
        ds.event_desc_text = _format_description(ev.description)
        ds.event_indicators_text = _format_indicators(ev.indicators)
        ds.event_rule_text = rule_text
        ds.event_raw_text = _format_raw(ev._raw)

        self._screen_manager.current = "detail"

    def go_back(self):
        """Navigate back to the main list screen."""
        self._screen_manager.current = "main"

    # ------------------------------------------------------------------
    # Status / overlay helpers
    # ------------------------------------------------------------------

    def _set_status(self, status: str):
        """Update the connection status label in the top bar."""
        labels = {
            "connecting": ("● Connecting…", (0.9, 0.8, 0.2, 1)),
            "connected": ("● Connected", (0.3, 0.85, 0.4, 1)),
            "error": ("● Auth Error", (0.85, 0.3, 0.3, 1)),
            "disconnected": ("● Disconnected", (0.6, 0.6, 0.6, 1)),
        }
        text, color = labels.get(status, labels["disconnected"])
        if self._status_label:
            self._status_label.text = text
            self._status_label.color = color

    def _show_loading(self, visible: bool):
        """Show or hide the loading overlay."""
        if self._loading_overlay is None:
            return
        if visible:
            self._loading_overlay.opacity = 1
            self._loading_overlay.disabled = False
        else:
            self._loading_overlay.opacity = 0
            self._loading_overlay.disabled = True

    def _show_error(self, message: str):
        """Display the full-screen authentication error overlay."""
        if self._error_overlay is None:
            return
        self._error_overlay.error_message = message
        self._error_overlay.opacity = 1
        self._error_overlay.disabled = False


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    """Launch the Tailored Intel Browser application.

    Credentials from -k/-s are scraped from sys.argv at module import time
    (before Kivy can consume -k/-s as its own fake-fullscreen / save flags)
    and stored in _PRE_IMPORT_CLIENT_ID / _PRE_IMPORT_CLIENT_SECRET.
    """
    TailoredIntelBrowserApp(
        client_id=_PRE_IMPORT_CLIENT_ID,
        client_secret=_PRE_IMPORT_CLIENT_SECRET,
    ).run()


if __name__ == "__main__":
    main()
