name: "Label Request"
on:
  pull_request:
    branches:
      - main
      - 'ver_*'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
