name: Unit testing (USGOV1)
on:
  push:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'

jobs:
  usgov1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        DEBUG_API_ID: ${{ secrets.DEBUG_API_ID_USGOV1 }}
        DEBUG_API_SECRET: ${{ secrets.DEBUG_API_SECRET_USGOV1 }}
        DEBUG_API_BASE_URL: usgov1
        CROSS_DEBUG_KEY: ${{ secrets.CROSS_DEBUG_KEY }}
        CROSS_DEBUG_SECRET: ${{ secrets.CROSS_DEBUG_SECRET }}
      run: |
        coverage run --source=src --omit=src/falconpy/debug.py -m pytest -s --ignore-glob=**/manual/*
        coverage report
