name: Unit testing (US2)
on:
  push:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'

jobs:
  us2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        DEBUG_API_ID: ${{ secrets.DEBUG_API_ID_US2 }}
        DEBUG_API_SECRET: ${{ secrets.DEBUG_API_SECRET_US2 }}
        DEBUG_API_BASE_URL: us2
        CROSS_DEBUG_KEY: ${{ secrets.CROSS_DEBUG_KEY }}
        CROSS_DEBUG_SECRET: ${{ secrets.CROSS_DEBUG_SECRET }}
      run: |
        coverage run --source=src --omit=src/falconpy/debug.py -m pytest -s
        coverage report
