name: Python package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - main
      - 'ver_*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        DEBUG_API_ID: ${{ secrets.DEBUG_API_ID }}
        DEBUG_API_SECRET: ${{ secrets.DEBUG_API_SECRET }}
      run: |
        coverage run --source=src --omit=src/falconpy/debug.py -m pytest -s
        coverage report
