name: Unit testing (Ubuntu / py3.6)
on:
  push:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
      - dev
  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
      - dev

jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.6']
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        DEBUG_API_ID: ${{ secrets.DEBUG_API_ID }}
        DEBUG_API_SECRET: ${{ secrets.DEBUG_API_SECRET }}
        CROSS_DEBUG_KEY: ${{ secrets.CROSS_DEBUG_KEY }}
        CROSS_DEBUG_SECRET: ${{ secrets.CROSS_DEBUG_SECRET }}
      run: |
        coverage run --source=src --omit=src/falconpy/debug.py -m pytest -s --ignore-glob=**/manual/*
        coverage report
